/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ToggleStencil {}
}

declare global {


  interface HTMLToggleStencilElement extends Components.ToggleStencil, HTMLStencilElement {}
  var HTMLToggleStencilElement: {
    prototype: HTMLToggleStencilElement;
    new (): HTMLToggleStencilElement;
  };
  interface HTMLElementTagNameMap {
    'toggle-stencil': HTMLToggleStencilElement;
  }
}

declare namespace LocalJSX {
  interface ToggleStencil {}

  interface IntrinsicElements {
    'toggle-stencil': ToggleStencil;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'toggle-stencil': LocalJSX.ToggleStencil & JSXBase.HTMLAttributes<HTMLToggleStencilElement>;
    }
  }
}


